### ISSUE TITLE
SA: handling of NaN

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#110]
Now it is not clear what happens if in SA an error in definition of the tree happens. It seems that table shows 0.0.
An error is eg. setting negative probability or logarithm of negative value.

My recommendation: show NaN in a table (if this is possible).
@mwasiluk: what is possible?

**Comment by mwasiluk** [comment]
If the tree is invalid payoff is set to string 'n/a' in the data passed to pivot table. 
It's treated as 0.0 in computed pivot cells because it's a result of a selected agregator function (which normally skips NaN values). 
N/A is visible in 'First'/'Last' agregator function and if payoff is set as column/row.

**Comment by bkamins** [comment]
Please implement the following functionality:
If there is any `n/a` in the results of the computations of the payoffs of the trees SA (N-way and Probabilistic) must not show SA results but should show an error dialog box:
> Error in sensitivity analysis computations for the following parameters:
> parameter1 = value1
> parameter2 = value2
> ...

And the parameterization should be any of the parameters that generate `n/a` (as there might be multiple).
After clicking OK user goes back to SA definition dialog.

**Comment by bkamins** [comment]
ok
