### ISSUE TITLE
Problem with exporting to png

### ISSUE THREAD

**Issue by TomaszStepien** [SilverDecisions/SilverDecisions#133]
When I exported my tree to png the background was black and the picture was not visible well

**Comment by mwasiluk** [comment]
Could you please attach your exported image? 
Exported png file is generated with the transparent background and some viewers may fill it with black color.

**Comment by TomaszStepien** [comment]
![tomasz_stepien_decisiontree_1_2017 05 19_11 11 17](https://cloud.githubusercontent.com/assets/19878292/26418509/c5bf3de8-40bc-11e7-94a9-ed2c776f14ea.png)

**Comment by TomaszStepien** [comment]
Ok, it does look normal here. So it must be Microsoft's fault. On windows and in Outlook preview it looks like this: 
![image](https://cloud.githubusercontent.com/assets/19878292/26418573/febbc88c-40bc-11e7-866d-c952e51fa7aa.png)

**Comment by bkamins** [comment]
Yes - this is a preview issue. Thanks anyway :).

**Comment by pszufe** [comment]
Just to have more detailed explanation for other users.
SilverDecisions saves PNG files with a transparent background. This is a very convenient if a tree image needs to be placed in some other document (e.g. a web page). 
Since the background is transparent different software can represent it in different ways - in most applications (e.g. MS Word, Microsoft Paint) the backgrounds color is displayed as white but some application could expose different behavior.
