### ISSUE TITLE
Reaction of the program to changes in the tree are delayed

### ISSUE THREAD

**Issue by JanuszSz** [SilverDecisions/SilverDecisions#134]
The problem with tree construction - the reaction of the program to changes in the tree are delayed.
Such situations occur when the operating memory is overloaded or the information packets are lost in the transmission to the server.
Suggestion: separate the optimization algorithm from the module of construction and tree change. 
Startup optimization should be done by clicking the "execute" button on the finished tree, and not active all the time (after selecting the optimization rule).

**Comment by bkamins** [comment]
@JanuszSz Thank you for the comment. We would gladly correct it, but please indicate at what actions the reaction is delayed (adding new node, editing data in the node, does it happen for any trees or only for large tress, etc.).

I am asking because (@mwasiluk - please correct me if I am wrong):
* optimization module is already separated form tree construction module;
* no transmission of the data between the server and client happens in the application - everything is on client side (except for initial loading of the website and export of images).

**Comment by JanuszSz** [comment]
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
Added picture.
Pozdrawiam _ Janusz

**Comment by bkamins** [comment]
Could you resend the picture please, because it did not paste correctly.

**Comment by JanuszSz** [comment]
@bkamins 
adding new node, moving trees
any tress (I have made small trees)
@mwasiluk
Optimization is working before I finished the tree. I do not decide to start the mode of optimization but the program. In this way, it is the program activity mode (optimizing), what is unnecessary use of operating memory.

**Comment by bkamins** [comment]
@mwasiluk in application add a button that disables automatic recalculation of the tree (useful when the tree is being designed). When disabled "raw" view should be presented.

**Comment by bkamins** [comment]
@mwasiluk actually - maybe current "raw" view could simply disable recalculation?

**Comment by mwasiluk** [comment]
Automatic recalculation should be now disabled in "raw" mode.
