### ISSUE TITLE
Add new type of terminal node: markov

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#143]
Add Markov terminal node type.

@michaljakubczyk please define specification of this type of terminal node before implementation.

**Comment by michaljakubczyk** [comment]
I have the following idea. Please comment. 

The user can add a new type of node – Markov chain (say, marked as hexagon with M letter inside. No children can be added to an M-node.

When the user clicks on the M-node no connections are displayed in the left panel. Instead, the user should be able to open a dialogue box defining the Markov node.

In the dialogue box the user first specifies the number of states, n (say 1 to 15, 1 as default when created). 

The matrix is presented with n rows & columns. The matrix is called “Transition probabilities”.
The first n rows & columns are named “State #1”, etc., by default. The user can change the name of the rows, and then the names of the columns follow automatically. As default, the content is the identity matrix (1 in main diagonal, 0 otherwise). Only non-negative, <=1 values are allowed. The dialogue box cannot be closed if the values do not sum to 100% in rows. Element p_{i,j} denotes the one-cycle probability of i-->j transition.

Copying from an imported grid can be considered here.

If n is increased, then additional rows & columns are added, with 1 in the main diagonal only. If n is decreased, then unnecessary rows & columns are deleted.

Below the transition matrix, a table is presented with n rows and the following columns:

1. initial probabilities
2. cost of entering a state
3. cost of staying in a state
4. cost of exiting a state
5. effect of entering a state
6. effect of staying in a state
7. effect of exiting a state

Do we allow formulas in the transition matrix & state characteristics? If so, can we use an internal cycle counter (say, variable .cycle that starts as 1, and is increased by 1 cycle by cycle).

Advantages:
1. The user can use discounting.
2. The user can modify pay-offs/probabilities in time (e.g. representing changing risk with age)

Disadvantages:
1. It will be more difficult to calculate the overall average cost & effect.

Finally, the user specifies the maximal number of cycles, T (required; if needed, can be limited to, e.g., 100). After, T-th cycle there are no transitions.

After defining the chain and closing the dialogue box, the expected cost and effect (or just one, depending on the number of criteria and the rule) should be displayed below the node.

**Comment by bkamins** [comment]
Having read the specification I would not implement it in SilverDecisions.
The functionality is completely orthogonal do decision trees.

However, we could develop a separate application for such calculations:
It could be a web application / excel file / R script - TBD (but as a separate project)
When we have it we can consider integrating it with SilverDecisions.

@michaljakubczyk @pszufe please comment how you see it.

**Comment by pszufe** [comment]
In later versions we should create some plugin architecture that enables terminal nodes.
Two plugin types could be considered:
- internalized GUI plaguns build with HTML+JavaScript
- externalized plugins enabling connection to external datasources with uncertainty. Preferably this could be done through a RESTfull API.

**Comment by bkamins** [comment]
@pszufe This is a general approach for the future. But how do you see current plan. Do you agree with me (create a separate project and consider integrating with it later) or want to have it as a part of SD?

**Comment by michaljakubczyk** [comment]
let's skip it for now, then, and maybe come back to it as a separate project
